apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hby9fwa12-java-quarkus-gitops-repository
spec:
  url: https://github.com/chetna14manku-org/hby9fwa12-java-quarkus-gitops